spring.application.name=RikkeiStore-Inventory-AOP
spring.datasource.url=jdbc:h2:file:./data/rikkeistore;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
